// Code generated by go-swagger; DO NOT EDIT.

package goods

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostPurchaseGoodsOKCode is the HTTP code returned for type PostPurchaseGoodsOK
const PostPurchaseGoodsOKCode int = 200

/*PostPurchaseGoodsOK ok

swagger:response postPurchaseGoodsOK
*/
type PostPurchaseGoodsOK struct {

	/*
	  In: Body
	*/
	Payload *PostPurchaseGoodsOKBody `json:"body,omitempty"`
}

// NewPostPurchaseGoodsOK creates PostPurchaseGoodsOK with default headers values
func NewPostPurchaseGoodsOK() *PostPurchaseGoodsOK {

	return &PostPurchaseGoodsOK{}
}

// WithPayload adds the payload to the post purchase goods o k response
func (o *PostPurchaseGoodsOK) WithPayload(payload *PostPurchaseGoodsOKBody) *PostPurchaseGoodsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post purchase goods o k response
func (o *PostPurchaseGoodsOK) SetPayload(payload *PostPurchaseGoodsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostPurchaseGoodsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
