// Code generated by go-swagger; DO NOT EDIT.

package goods

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// SetGoodsOKCode is the HTTP code returned for type SetGoodsOK
const SetGoodsOKCode int = 200

/*SetGoodsOK ok

swagger:response setGoodsOK
*/
type SetGoodsOK struct {

	/*
	  In: Body
	*/
	Payload *SetGoodsOKBody `json:"body,omitempty"`
}

// NewSetGoodsOK creates SetGoodsOK with default headers values
func NewSetGoodsOK() *SetGoodsOK {

	return &SetGoodsOK{}
}

// WithPayload adds the payload to the set goods o k response
func (o *SetGoodsOK) WithPayload(payload *SetGoodsOKBody) *SetGoodsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the set goods o k response
func (o *SetGoodsOK) SetPayload(payload *SetGoodsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SetGoodsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
