// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetWalletOKCode is the HTTP code returned for type GetWalletOK
const GetWalletOKCode int = 200

/*GetWalletOK ok

swagger:response getWalletOK
*/
type GetWalletOK struct {

	/*
	  In: Body
	*/
	Payload *GetWalletOKBody `json:"body,omitempty"`
}

// NewGetWalletOK creates GetWalletOK with default headers values
func NewGetWalletOK() *GetWalletOK {

	return &GetWalletOK{}
}

// WithPayload adds the payload to the get wallet o k response
func (o *GetWalletOK) WithPayload(payload *GetWalletOKBody) *GetWalletOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get wallet o k response
func (o *GetWalletOK) SetPayload(payload *GetWalletOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWalletOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
