// Code generated by go-swagger; DO NOT EDIT.

// Package restapi fabric goods sample
//
//  Schemes:
//    http
//  Host: localhost:8080
//  BasePath: /v1
//  Version: 1.6
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
