// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "fabric goods sample",
    "version": "1.6"
  },
  "host": "localhost:8080",
  "basePath": "/v1",
  "paths": {
    "/getAllGoods": {
      "get": {
        "tags": [
          "Goods"
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "category": {
                    "type": "string"
                  },
                  "key": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "price": {
                    "type": "integer",
                    "format": "int64",
                    "x-omitempty": false
                  },
                  "walletId": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/getWallet": {
      "get": {
        "tags": [
          "Wallet"
        ],
        "operationId": "getWallet",
        "parameters": [
          {
            "type": "string",
            "name": "walletId",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "token": {
                  "type": "integer",
                  "format": "int64",
                  "x-omitempty": false
                }
              }
            }
          }
        }
      }
    },
    "/purchaseGoods": {
      "post": {
        "tags": [
          "Goods"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "key": {
                  "description": "goods key",
                  "type": "string"
                },
                "walletId": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int64"
                },
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/setGoods": {
      "post": {
        "tags": [
          "Goods"
        ],
        "operationId": "setGoods",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "category": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "price": {
                  "type": "integer",
                  "format": "int64"
                },
                "walletId": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int64"
                },
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "fabric goods sample",
    "version": "1.6"
  },
  "host": "localhost:8080",
  "basePath": "/v1",
  "paths": {
    "/getAllGoods": {
      "get": {
        "tags": [
          "Goods"
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/GetGetAllGoodsOKBodyItems0"
              }
            }
          }
        }
      }
    },
    "/getWallet": {
      "get": {
        "tags": [
          "Wallet"
        ],
        "operationId": "getWallet",
        "parameters": [
          {
            "type": "string",
            "name": "walletId",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "token": {
                  "type": "integer",
                  "format": "int64",
                  "x-omitempty": false
                }
              }
            }
          }
        }
      }
    },
    "/purchaseGoods": {
      "post": {
        "tags": [
          "Goods"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "key": {
                  "description": "goods key",
                  "type": "string"
                },
                "walletId": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int64"
                },
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/setGoods": {
      "post": {
        "tags": [
          "Goods"
        ],
        "operationId": "setGoods",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "category": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "price": {
                  "type": "integer",
                  "format": "int64"
                },
                "walletId": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int64"
                },
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "GetGetAllGoodsOKBodyItems0": {
      "type": "object",
      "properties": {
        "category": {
          "type": "string"
        },
        "key": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "price": {
          "type": "integer",
          "format": "int64",
          "x-omitempty": false
        },
        "walletId": {
          "type": "string"
        }
      }
    }
  }
}`))
}
